# Generated by Django 3.2.6 on 2021-08-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
    ]
