# Generated by Django 3.2.6 on 2021-08-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0003_product_is_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='distributor.Tag'),
        ),
    ]
